include "SystemDefines.inc"

ext	updateSpriteAttributes
ext	updateSpriteAttributeTable

dseg

nmiCount:	public nmiCount
    ds	1

lastNMICount:	public lastNMICount
	ds	1

cseg

nmiHandler: public nmiHandler
	rti

irqHandler:	public irqHandler
	pha
	phx
	phy

	lda		InterruptIOPort
	
	bit		#1						; Interrupt enerated by TMS-9918 VBlank?
	beq		checkInput

	inc		nmiCount

	lda		updateSpriteAttributes
	beq		exitTMSUpdate

	jsr		updateSpriteAttributeTable

exitTMSUpdate:
	bit		VDPBase + WriteOffset	; Clear TMS-9918 interrupt.
	jmp		exitIRQHandler

checkInput:							; Interrupt generated by keyboard or NES controllers?
	bit		#2
	beq		exitIRQHandler

	bit		KeyboardIOPort			; Clear IO interrupt.
	bit		KeyboardIOPort + 1

exitIRQHandler:
	ply
	plx
	pla
	
	rti
